### ISSUE TITLE
你好作者

### ISSUE THREAD

**Issue by we1lless** [yangdayangda/cardRecorder#1]
我尝试运行安装了该APP，牌数仅在点击开始按钮后有所改变，之后的牌数都没有变化

**Comment by yangdayangda** [comment]
如果在开始时点数有变化，那么说明程序识别牌的点数是没有问题的，之后牌数不变，可能是识别速度比较慢。我在几个手机上实验都没有问题，你可以把你录制的错误视频发给我看一下
