### ISSUE TITLE
报错Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

### ISSUE THREAD

**Issue by we1lless** [yangdayangda/cardRecorder#2]
我尝试运行安装了该APP，牌数仅在点击开始按钮后有所改变，定时任务也在运行但之后的牌数都没有变化，之后一直报这个警告Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

**Comment by yangdayangda** [comment]
这应该是内存空间不足导致的问题

**Comment by we1lless** [comment]
手机内存空间是够的，这个项目还会维护完善吗作者，上次草草运行看了一下代码，今天晚上再去看看代码

**Comment by yangdayangda** [comment]
应该不会维护了，你这种情况我没办法复现，也不知道是怎么造成的，你可以试试其他手机会不会出现该情况
