### ISSUE TITLE
记牌器有负数

### ISSUE THREAD

**Issue by andy4lee** [yangdayangda/cardRecorder#3]
你好，我没用错地方吧，请问是小程序版的欢乐斗地主吗？发现个小问题，记牌器有负数
![528d32c2d62fa5a33bc7f8eafdd5fe2](https://github.com/yangdayangda/cardRecorder/assets/38412895/66b5c0b0-1dd5-4911-bc8b-af18c834fc2f)

**Comment by yangdayangda** [comment]
没用错地方就是微信小程序的欢乐斗地主，由于该记牌器使用截图的方式获取内容，且存在截图间隔，所以存在出现负数的情况。
例如你上述图片，如果刚好在出现KQ976时截图，后续的4个5还没来得及出现，最后就会减掉俩次KQ976而出现负数。另外每次游戏开始时都需要重新点击开始。
