### ISSUE TITLE
记牌器移植到别的游戏的一些问题

### ISSUE THREAD

**Issue by MDsuccess** [yangdayangda/cardRecorder#4]
你好，我想请问一下FloatWindowService类里面的ratio为什么是固定由屏幕高度除3200得到的呀？另外，程序的识别资源是不是需要固定大小才能保证准确率呢，我看你的资源都是固定大小的，这些资源是怎么获取到的呢，我也尝试手动替换了单机版本的欢乐斗地主的一些图片，发现识别效果并不好。望回复，万分感谢！！

**Comment by yangdayangda** [comment]
该程序使用的是opencv的模版匹配技术，只有当两个图片里的内容大小一致时才能进行匹配，所以需要对图片进行缩放，由于当时开发时使用的手机尺寸是3200的，所以要把尺寸缩放一致

**Comment by MDsuccess** [comment]
明白，所以我在2400尺寸上的设备使用时应该将这里修改成2400

**Comment by yangdayangda** [comment]
是的，如果你移植到其他游戏需要重新截图，才能使用。

**Comment by MDsuccess** [comment]
还想了解一下手牌和对方出牌的区域范围是怎么确定的呢，是通过截屏直接在图片上测量范围获取的吗，这里面是否有数据处理过程呢？为什么这些区域的数据也需要乘一次比例呀？有点迷惑哈哈。

**Comment by micholeh** [comment]
能联系你一下么。我想有尝修改一下

**Comment by yangdayangda** [comment]
> 能联系你一下么。我想有尝修改一下

qq:2842635969
